server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/subscription_db?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topic: "create-post-topic"
    groupId: "create-post-group-id"